name: .NET CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore MyApi.sln

      - name: Build solution
        run: dotnet build MyApi.sln -c Release --no-restore

      - name: Publish application
        run: dotnet publish MyApi/MyApi.csproj -c Release -o ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: ./publish
