name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # Restore NuGet packages
      - name: Restore
        run: dotnet restore

      # Build project (Release)
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Run tests (optional but good practice)
      - name: Test
        run: dotnet test --configuration Release --no-build

      # Publish app into /publish folder
      - name: Publish
        run: dotnet publish -c Release -o ./publish

      # Upload publish folder as artifact so you can download it
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-build
          path: ./publish
